const champions = {
  2018: { game: 'ROVER RUCKUS / 2018–19', title: 'HIGH-REACH\nMINERAL BOT', copy: 'A compact scoring machine built around a vertical lift and a repeatable mineral delivery path. Its narrow profile made depot alignment and endgame parking less dramatic.', stats: ['4', '2', '360°'], notes: 'The architecture is all about a clean handoff: collect from the floor, index the game piece, then raise only as far as the scoring path requires. Shorter travel time makes every autonomous and tele-op cycle more dependable.' },
  2019: { game: 'SKYSTONE / 2019–20', title: 'LATERAL\nBLOCK RUNNER', copy: 'A low center of mass and side-facing intake make rapid foundation-side cycles possible. The best designs reduced every block handoff to a single, predictable motion.', stats: ['4', '3', '2×'], notes: 'The lateral collector lets a driver acquire blocks while maintaining a favorable chassis heading. A staged lift separates pickup, travel, and placement so the robot can score accurately without giving up speed.' },
  2022: { game: 'FREIGHT FRENZY / 2021–22', title: 'FREIGHT\nCYCLE BOT', copy: 'A wide funnel intake, turret-style delivery geometry, and compact outtake work together to turn loose freight into scoring cycles.', stats: ['4', '1', '270°'], notes: 'Funnel geometry matters here: wide enough to forgive imperfect driver alignment, constrained enough to center freight for the handoff. The delivery mechanism concentrates precision where it has the highest payoff—at the hub.' },
  2024: { game: 'CENTERSTAGE / 2023–24', title: 'PIXEL\nPLACEMENT BOT', copy: 'A deliberate combination of pixel intake, controlled vertical travel, and compliant end effector prioritizes accurate backdrop placement.', stats: ['4', '2', '6'], notes: 'This machine treats each pixel as a controlled payload. Compliance in the end effector gives a small alignment window at the backdrop; a stable lift keeps that placement repeatable after dozens of cycles.' }
};
const parts = {
  drive: { index:'01', title:'MECANUM\nDRIVETRAIN', kicker:'SYSTEM 01', callA:'OMNI WHEELS', callB:'POWER PATH', meter:'94%', width:'94%', copy:'Angled rollers let each wheel add a different vector. Paired with good control code, the chassis can strafe into scoring position without rotating away from the target.' },
  intake: { index:'02', title:'COMPLIANT\nINTAKE', kicker:'SYSTEM 02', callA:'GUIDE ROLLERS', callB:'FLOOR PATH', meter:'88%', width:'88%', copy:'Soft wheels and shaped guides turn a broad pickup zone into a centered game piece. The mechanism absorbs small alignment mistakes, keeping drivers focused on the next target.' },
  lift: { index:'03', title:'CASCADING\nLIFT', kicker:'SYSTEM 03', callA:'BELT STAGES', callB:'HARD STOPS', meter:'91%', width:'91%', copy:'A staged slide packages long reach into a compact starting envelope. Tensioned belts and physical stops protect position repeatability, especially when the robot changes direction quickly.' },
  arm: { index:'04', title:'ARTICULATED\nEND EFFECTOR', kicker:'SYSTEM 04', callA:'PIVOT JOINT', callB:'GRIP WINDOW', meter:'96%', width:'96%', copy:'The final few inches decide whether a cycle scores. A jointed arm changes approach angle while a compliant claw holds the piece securely, then releases without dragging it off target.' }
};
const $ = s => document.querySelector(s);
document.querySelectorAll('.year').forEach(button => button.addEventListener('click', () => {
  const data = champions[button.dataset.year]; document.querySelectorAll('.year').forEach(b => { b.classList.remove('active'); b.setAttribute('aria-selected','false'); }); button.classList.add('active'); button.setAttribute('aria-selected','true');
  $('#cardYear').textContent = button.dataset.year; $('#cardGame').textContent = data.game; $('#cardTitle').innerHTML = data.title.replace('\n','<br>'); $('#cardCopy').textContent = data.copy;
  ['cardStat1','cardStat2','cardStat3'].forEach((id,i) => $('#'+id).textContent=data.stats[i]); $('#championCard').animate([{opacity:.35,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:280});
}));
document.querySelectorAll('.part').forEach(button => button.addEventListener('click', () => { const p=parts[button.dataset.part]; document.querySelectorAll('.part').forEach(b=>b.classList.remove('active'));button.classList.add('active');$('#stageIndex').textContent=p.index;$('#detailKicker').textContent=p.kicker;$('#detailTitle').innerHTML=p.title.replace('\n','<br>');$('#detailCopy').textContent=p.copy;$('#calloutA').innerHTML=`<span>${p.index}</span><b>${p.callA}</b><i></i>`;$('#calloutB').innerHTML=`<span>${String(+p.index+1).padStart(2,'0')}</span><b>${p.callB}</b><i></i>`;$('#meter').style.width=p.width;$('#meterValue').textContent=p.meter;$('#anatomyRobot').animate([{transform:'scale(1.9) rotate(-2deg)'},{transform:'scale(1.9) rotate(0)'}],{duration:360}); }));
$('#motionToggle').addEventListener('click', e=>{document.body.classList.toggle('motion-off');const paused=document.body.classList.contains('motion-off');e.currentTarget.setAttribute('aria-pressed',paused);e.currentTarget.lastChild.textContent=paused?' PLAY MOTION':' PAUSE MOTION';});
const dialog=$('#inspectDialog');$('#inspectButton').addEventListener('click',()=>{const active=document.querySelector('.year.active').dataset.year,d=champions[active];$('#dialogTitle').innerHTML=d.title.replace('\n','<br>');$('#dialogBody').textContent=d.notes;dialog.showModal();});$('#closeDialog').addEventListener('click',()=>dialog.close());
